version: "3"

services:

    nodejs:
        restart: unless-stopped
        build:
            context: ./nodejs
            dockerfile: DockerFile
        env_file: nodejs.env
        container_name: phone-nodejs
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        ports:
         - "3333:3333"
        command: "npm start"

    gammu:
        restart: unless-stopped
        build:
          context: ./gammu
          dockerfile: DockerFile
        container_name: phone-gammu
        devices:
            - "/dev/ttyUSB1:/dev/ttyUSB1:rwm"    
        depends_on: 
            - mysql

    mysql:
        restart: unless-stopped
        image: mariadb:10.3
        container_name: phone-mysql
        volumes:
            - ./mysql/gammu/mysql-strict.sql:/docker-entrypoint-initdb.d/init.sql
            - /home/xxx/docker-data/phone-mysql/data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}           
